# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Elias Strehle
title: Software Engineer and Researcher
email: strehle.elias@gmail.com

darkmode: false

# Social links
github_username:  estrehle
linkedin_username: elias-strehle-474a11128
orcid_username: 0000-0002-4351-7865

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  After studying business administration and financial mathematics, I completed my PhD in mathematics in 2017.
  Since then I have worked in IT - as a Python data engineer, blockchain researcher and TypeScript full-stack developer.

  My passion is to make complicated things work.
  I enjoy teaching myself and others complex concepts, from mathematics to machine learning and software architecture (which is why I loved academic research).
  And I enjoy building things that put these concepts to work and make a difference in real life (which is why I left academic research).


content:
  - title: IT Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Fullstack Development
        description: | # this will include new lines to allow paragraphs
          I taught myself TypeScript/JavaScript in early 2021.
          Since then I have built several prototypes of full-stack applications.
          My current default tech stack includes the Angular and Nest.js frameworks, MySQL, Docker, GitHub and AWS (EC2, RDS, Amplify, Lightsail).
          Take a look at my showcase [server-to-server chat application](https://github.com/estrehle/webchat) to see how I code.

          As much as I enjoy programming, I view it as a tool to accomplish things that are useful.
          My best moments as a developer were not spent in front of my IDE but in conversations with smart and passionate people.
      - layout: left
        title: Decentralized Data Exchanges
        description: |
          Much of my recent work has revolved around decentralized data exchanges.
          These are computer networks where data is stored and controlled by its owners instead of a central agent.
          My personal focus within this area has been on the (in-)applicability of blockchain technology and [self-sovereign identity](https://en.wikipedia.org/wiki/Self-sovereign_identity) frameworks.
          Some of my outputs are publicly available, including a [blog post](https://www.blockchainresearchlab.org/2020/12/11/enterprise-dlt-the-leaky-trust-machine-2/) on blockchain's confidentiality issues
          and a [working paper](https://www.blockchainresearchlab.org/wp-content/uploads/2020/05/BRL-Working-Paper-No-18-DibiChain.pdf) sketching a privacy-preserving decentralized data exchange.

          Currently I am part of the [BloGÂ³ research project](https://www.blog3.de/) (link in German) which aims to give patients autonomy over their medical data.
          My contribution to the project includes co-architecting and co-implementing a decentralized data exchange built on top of the [Hyperledger Aries](https://www.hyperledger.org/use/aries) toolkit.
          Unfortunately, the results are not (yet) public.
      - layout: left
        title: Data Engineering and Machine Learning
        description: |
          I have experience in various stages of the data processing life cycle, including automated data import from REST APIs,
          data modeling and transformation in TypeScript and Python,
          interaction with relational databases through ORMs and SQL
          as well as basic knowledge of machine learning and deep learning.
          For a developer, my aversion to Microsoft Office is unusually low, and I enjoy explaining and presenting data to all kinds of audiences.

  - title: Professional Experience
    layout: list
    content:
    - layout: top-middle
      title: CTO
      sub_title: CircularTree
      caption: April 2021 - Present
      link: https://www.circulartree.com/
      link_text: circulartree.com
    - layout: top-middle
      title: Blockchain Researcher
      sub_title: Blockchain Research Lab
      caption: August 2019 - April 2021
    - layout: top-middle
      title: Python Software Engineer and Data Scientist
      sub_title: Yieldlove
      caption: June 2018 - August 2019
    - layout: top-middle
      title: Data Engineer and Data Scientist
      sub_title: Rheindata
      caption: January 2018 - June 2018
    - layout: top-middle
      title: Research Assistant
      sub_title: University of Mannheim
      caption: October 2014 - December 2017

  - title: Education
    layout: list
    content:
    - layout: top-middle
      title: Dr. rer. nat. Financial Mathematics (summa cum laude)
      sub_title: University of Mannheim
      caption: 2014 - 2017
    - layout: top-middle
      title: M.Sc. Financial Mathematics
      sub_title: Christian-Albrecht University of Kiel
      caption: 2012 - 2014
    - layout: top-middle
      title: B.Sc. Business Administration
      sub_title: University of Mannheim
      caption: 2008 - 2011

# Footer
footer_show_references: true
references_title: Built with Matt Sproogen's Modern Resume Theme (https://github.com/sproogen/modern-resume-theme)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
